<?php

namespace AppBundle\Repository;

/**
 * CodeSectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CodeSectionRepository extends BaseRepository
{
}
