<?php

namespace AppBundle\Repository;

/**
 * DesignSectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DesignSectionRepository extends BaseRepository
{
}
