<?php

namespace AppBundle\Repository;

/**
 * GeneralInfoSectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeneralInfoSectionRepository extends \Doctrine\ORM\EntityRepository
{
}
