<?php

namespace AppBundle\Repository;

/**
 * MakeupSectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MakeupSectionRepository extends \Doctrine\ORM\EntityRepository
{
}
