<?php

namespace AppBundle\Repository;

/**
 * MarketingSectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarketingSectionRepository extends \Doctrine\ORM\EntityRepository
{
}
