<?php

namespace AppBundle\Repository;

/**
 * ModuleSectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuleSectionRepository extends \Doctrine\ORM\EntityRepository
{
}
