<?php

namespace AppBundle\Repository;
use AppBundle\Entity\ModuleSection;
use Symfony\Component\Form\Form;
use Symfony\Component\HttpFoundation\Request;

/**
 * ModuleSectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuleSectionRepository extends BaseRepository
{
    public function addDataClassToSession($formName, ModuleSection $dataClass, Request $request = null, Form $form = null)
    {
        $dataClass = $dataClass->
        setSiteModules($this->
        getModules($request->request->get($form->getName())));
        
        parent::addDataClassToSession($formName, $dataClass, $request);
    }

    private function getModules($data)
    {
        $result = '';
        foreach ($data as $module => $value)
            if ($value && $module != '_token')
                $result = $result . $value . ', ';

        return trim($result, ', ');

    }
}
