<?php

namespace AppBundle\Repository;

/**
 * SiteGeneralInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiteGeneralInfoRepository extends \Doctrine\ORM\EntityRepository
{
}
