<?php

namespace AppBundle\Repository;

/**
 * TechDesignSectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TechDesignSectionRepository extends BaseRepository
{
}
