# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
#parameters:
#    parameter_name: value

#services:
#    company_repository:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

services:
    validator.unique.unique_constraint_validator:
                    class: AppBundle\Validator\Constraints\UniqueConstraintValidator
                    tags:
                        - { name: validator.constraint_validator, alias: unique_constraint_validator }
                    arguments: ['@doctrine.orm.entity_manager']